services:
  postgres:
    image: postgres:15
    container_name: postgres-todolist
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todolist
    ports:
      - '54321:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  